### ISSUE TITLE
[refactor]: Remove debug log in `module.utils.ts`

### ISSUE THREAD

**Issue by ravut8** [logicspark/berryjam#14]
### Overview
I've noticed that this log is always displayed, which may not be necessary within the library. If users wish to view log information, they can use the `verbose` option instead

https://github.com/logicspark/berryjam/blob/53a1eb4e70cec12e72b1a0a3d9d8d589d26acba6/src/utils/module.utils.ts#L247

### Expected Behavior
Remove the line and the code still work per normal.

**Comment by jobayer12** [comment]
@ravut8 Review my pull request
