### ISSUE TITLE
✨ Export `GitService` class or create a public method for external use in `VueScanner` class

### ISSUE THREAD

**Issue by ravut8** [logicspark/berryjam#41]
### Description

Currently, the GitService class is not accessible for use in Berryjam CLI or any other applications. To make it available for external use, we need to solve this issue.

### Why is this feature needed? Is there a problem that you faced?

By making this change, we enhance the reusability of the codebase, enabling external tools to benefit from the capabilities of the GitService class.

### What is the solution you have in mind?

We can take one of the following approaches:
1. Export `GitService` Class: We can export the GitService class so that other parts of the application or external applications can import and use it.
2. Create a Public Method: Another option is to create a public method within the `VueScanner` class that allows external applications, such as Berryjam CLI, to access the functionality provided by GitService.

**Comment by kittisakLS** [comment]
I'm planning to create a new method in `VueScanner` to simplify its use for other applications, eliminating the need for them to understand the intricacies of the `GitService` class.
