### ISSUE TITLE
✨ Scan 'pages' directory without marking files as components

### ISSUE THREAD

**Issue by kittisakLS** [logicspark/berryjam#56]
### Description

In a Nuxt.js project, the `pages` directory is used to store all page components. While scanning the project for components, it's important to include the pages directory for comprehensive analysis. However, the issue arises when files within the pages directory are incorrectly marked as components.

### Why is this feature needed? Is there a problem that you faced?

As it stands, the component scanner may mistakenly identify files within the pages directory as components. The component scanner should include the `pages` directory during the scanning process but should not mark the files within it as components. This ensures that page components are properly distinguished from other components in the project.

### What is the solution you have in mind?

Adjust the component scanning process to exclude the `pages` directory from being marked as components, while still scanning it for other purposes. This way, the distinction between page components and other components in the project is maintained.

### Additional Information

- Nuxt.js version: 3.x.x

This issue is essential for ensuring the accurate identification of components in Nuxt.js projects. Your attention to this matter is greatly appreciated.

**Comment by kittisakLS** [comment]
@ravut8 Please review

**Comment by ravut8** [comment]
@kittisakLS Looks good, feel free to continue with this issue.
